name: mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dropdown_search: ^5.0.2
  email_validator: ^2.1.16
  fancy_password_field: ^1.0.4
  file_picker: ^5.0.1
  flutter_secure_storage: ^5.0.2
  get: 4.6.5
  http: ^0.13.4
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  share_plus: ^4.0.10
  sliding_up_panel: ^2.0.0+1
  dartz: ^0.10.1
  intl: ^0.17.0
  freezed_annotation: ^2.1.0
  intl_phone_field: ^3.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true
